version: '2'

networks:
  app-tier:
    driver: bridge

services:

  redis:
    image: 'bitnami/redis:6.0'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=611191
      - REDIS_MASTER_SET=mymaster
    networks:
      - app-tier
    ports:
      - '6390:6379'

  redis-slave:
    image: 'bitnami/redis:6.0'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=611191
      - REDIS_PASSWORD=611191
    ports:
      - '6391:6379'
    depends_on:
      - redis
    networks:
      - app-tier

  redis-sentinel:
    image: 'bitnami/redis-sentinel:6.0'
    environment:
      - REDIS_MASTER_PASSWORD=611191
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26379-26381:26379'
    networks:
      - app-tier
